r = [
    {
        "id": "C-1",
        "kind": "Crew",
        "type": 1,
        "name": "Interagency Hotshot Crew (IHC)",
        "unit": "20-person",
        "category": "Personnel",
        "daily_rate_approx": 12000,
        "production_rate_chains_hr": 15
    },
    {"id": "C-2", "kind": "Crew", "type": 2, "name": "Hand Crew", "unit": "20-person", "category": "Personnel",
     "daily_rate_approx": 8000, "production_rate_chains_hr": 8},
    {"id": "C-10", "kind": "Smokejumpers", "type": 1, "name": "Smokejumper Load", "unit": "8-person",
     "category": "Personnel", "daily_rate_approx": 15000, "production_rate_chains_hr": 10},
    {"id": "C-20", "kind": "Helitack", "type": 2, "name": "Helitack Crew", "unit": "10-person", "category": "Personnel",
     "daily_rate_approx": 9000, "production_rate_chains_hr": 5},
    {"id": "E-1", "kind": "Engine", "type": 1, "name": "Structure Engine", "unit": "Vehicle", "tank_gal": 300,
     "pump_gpm": 1000, "category": "Equipment"},
    {"id": "E-3", "kind": "Engine", "type": 3, "name": "Wildland Engine (4x4)", "unit": "Vehicle", "tank_gal": 500,
     "pump_gpm": 150, "category": "Equipment"},
    {"id": "E-6", "kind": "Engine", "type": 6, "name": "Wildland Brush Truck", "unit": "Vehicle", "tank_gal": 150,
     "pump_gpm": 50, "category": "Equipment"},
    {"id": "D-1", "kind": "Dozer", "type": 1, "name": "Heavy Dozer (D8/D7)", "unit": "Vehicle", "category": "Equipment",
     "production_rate_chains_hr": 60},
    {"id": "D-3", "kind": "Dozer", "type": 3, "name": "Light Dozer (D4/D5)", "unit": "Vehicle", "category": "Equipment",
     "production_rate_chains_hr": 30},
    {"id": "WT-1", "kind": "Water Tender", "type": 1, "name": "Tactical Water Tender", "unit": "Vehicle",
     "tank_gal": 2000, "pump_gpm": 250, "category": "Equipment"},
    {"id": "WT-2", "kind": "Water Tender", "type": 2, "name": "Support Water Tender", "unit": "Vehicle",
     "tank_gal": 4000, "pump_gpm": 200, "category": "Equipment"},
    {"id": "A-1", "kind": "Air Tanker", "type": 1, "name": "Large Air Tanker (LAT)", "unit": "Aircraft",
     "capacity_gal": 3000, "category": "Aircraft"},
    {"id": "A-2", "kind": "Air Tanker", "type": 2, "name": "Very Large Air Tanker (VLAT)", "unit": "Aircraft",
     "capacity_gal": 9400, "category": "Aircraft"},
    {"id": "H-1", "kind": "Helicopter", "type": 1, "name": "Heavy Helicopter (Type 1)", "unit": "Aircraft",
     "capacity_gal": 700, "category": "Aircraft"},
    {"id": "H-3", "kind": "Helicopter", "type": 3, "name": "Light Helicopter (Type 3)", "unit": "Aircraft",
     "capacity_gal": 100, "category": "Aircraft"},
    {"id": "NFES-0670", "kind": "Pump", "type": "Mark-3", "name": "Portable High Pressure Pump", "unit": "Each",
     "category": "Cache-Trackable"},
    {"id": "NFES-0007", "kind": "Safety", "type": "Shelter", "name": "Fire Shelter (Standard)", "unit": "Each",
     "category": "Cache-Durable"},
    {"id": "NFES-1230", "kind": "Hose", "type": "1.5 inch", "name": "Lined Fire Hose", "unit": "50ft Section",
     "category": "Cache-Durable"},
    {"id": "NFES-0606", "kind": "Chemical", "type": "Retardant", "name": "Phos-Chek Retardant Powder", "unit": "Ton",
     "category": "Cache-Consumable"},
    {"id": "NFES-0715", "kind": "Food", "type": "MRE", "name": "Meals Ready to Eat", "unit": "Case",
     "category": "Cache-Consumable"}

]
